In [ ]:

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
# Example sequence data
sequences = [
 "cat and dog",
 "dog and bird",
 "bird in the sky",
 "fish in the ocean"
]
# Tokenize the sequences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sequences)
# Convert text sequences to integer sequences
integer_sequences = tokenizer.texts_to_sequences(sequences)
# Pad sequences to a fixed length
max_len = max(map(len, integer_sequences))
padded_sequences = pad_sequences(integer_sequences, maxlen=max_len, padding='post')
# One-hot encode the padded sequences
one_hot_encoded = np.zeros((len(padded_sequences), max_len, len(tokenizer.word_index) + 1),
dtype=int)
for i, sequence in enumerate(padded_sequences):
 for j, index in enumerate(sequence):
  one_hot_encoded[i, j, index] = 1
print("Original Sequences:")
print(sequences)
print("\nOne-Hot Encoded Sequences:")
print(one_hot_encoded)

Original Sequences:
['cat and dog', 'dog and bird', 'bird in the sky', 'fish in the ocean']

One-Hot Encoded Sequences:
[[[0 0 0 0 0 0 1 0 0 0]
  [0 1 0 0 0 0 0 0 0 0]
  [0 0 1 0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0]]

 [[0 0 1 0 0 0 0 0 0 0]
  [0 1 0 0 0 0 0 0 0 0]
  [0 0 0 1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 1 0 0 0 0 0 0]
  [0 0 0 0 1 0 0 0 0 0]
  [0 0 0 0 0 1 0 0 0 0]
  [0 0 0 0 0 0 0 1 0 0]]

 [[0 0 0 0 0 0 0 0 1 0]
  [0 0 0 0 1 0 0 0 0 0]
  [0 0 0 0 0 1 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 1]]]
